# Generated by Django 3.0.7 on 2020-06-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_user',
            new_name='item_purchaser',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_outcome',
        ),
        migrations.AddField(
            model_name='item',
            name='item_cost',
            field=models.IntegerField(default=0, verbose_name='Select outcome'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.TextField(max_length=10, verbose_name='Select name of event'),
        ),
    ]
