# Generated by Django 3.0.7 on 2020-06-24 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20200624_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_cost',
            field=models.IntegerField(default=0, verbose_name='Enter cost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Enter date of purchase'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.TextField(max_length=10, verbose_name='Select name of item'),
        ),
    ]
